"""Write the voiceover script for the rough cut, timed from its real timeline.

Reads docs/internal/video/demo-cut.timeline.json (written by tools/cut_demo.py) and writes
docs/internal/VOICEOVER-SCRIPT.md: each line with the moment it starts in demo-cut.mp4, the
seconds it may take, and whether the app is speaking there. Rerun after any new cut.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TIMELINE = ROOT / "docs" / "internal" / "video" / "demo-cut.timeline.json"
OUT = ROOT / "docs" / "internal" / "VOICEOVER-SCRIPT.md"
WPS = 2.4  # comfortable speaking pace, words per second

# (section names it covers, app audio during those sections, the line or None for silence)
BLOCKS = [
    (["Title card", "Home: the four steps", "Bolo: consent first"], None,
     "About half of all PMKVY skill certificates come through Recognition of Prior Learning. "
     "AnubhavPramaan makes that assessment fair and verifiable. It starts with consent."),
    (["Bolo: the app asks question 1 aloud"], "the app reads the question in Hindi", None),
    (["Bolo: the worker answers"], "the worker answers in Hindi", None),
    (["Bolo: what the AI heard, in the worker's words"], None,
     "The AI marks what the worker did, in their own words."),
    (["Bolo: answer 3, how they do the wiring"], "the worker explains the wiring", None),
    (["Bolo: claims for answer 3"], None,
     "Every claim keeps a quote for the assessor to check. In production, speech runs on Bhashini."),
    (["Bolo: read back to the worker"], "the app reads the summary back, from about 5 seconds in",
     "Before anything counts, it is read back to the worker."),
    (["Bolo: the worker confirms"], None,
     "They confirm, and the declaration goes to the assessor."),
    (["Milao: qualification match and the 70% rule"], None,
     "Milao matches the declaration to the NSQF Qualification Pack, criterion by criterion, and "
     "applies NCVET's own seventy percent rule for direct assessment. The tool suggests; the "
     "assessor decides."),
    (["Parkho: anchored checklist and a measured criterion"], None,
     "On the assessor's tablet, every criterion has written anchors and the worker's own words. "
     "Measured items, like saddle spacing within five hundred millimetres, are scored by rule. "
     "Photos are hashed on the device."),
    (["Parkho: the AI hint asks", "Parkho: the hint says only what it can see"], None,
     "The AI hint says only what it can see in the photo. It never gives a score."),
    (["Parkho: offline, then sync"], None,
     "With no network at the camp, scoring keeps working, and syncs later."),
    (["Pramaan: PIN sign-off by the assessor"], None,
     "Only the assessor can sign, with a PIN, even offline."),
    (["Pramaan: the verifiable record"], None,
     "The record is tamper-evident, and anyone can verify it by QR."),
    (["Samaan: consistency between assessors"], None,
     "Samaan measures how consistently assessors score the same evidence, with statistics "
     "checked against published results."),
    (["End card"], None, "AnubhavPramaan. AI suggests; the assessor decides."),
]


def mmss(t: float) -> str:
    return f"{int(t // 60)}:{t % 60:04.1f}"


def main() -> None:
    tl = json.loads(TIMELINE.read_text(encoding="utf-8"))
    sec = {s["section"]: s for s in tl["sections"]}
    rows, words_total, holds = [], 0, []
    for k, (names, app, line) in enumerate(BLOCKS, start=1):
        start = sec[names[0]]["start"]
        length = sum(sec[n]["length"] for n in names)
        words = len(line.split()) if line else 0
        need = words / WPS
        words_total += words
        over = need - length
        if line and over > 0.4:
            holds.append(f"Block {k}: the line needs about {need:.0f} s but the picture has {length:.0f} s. "
                         f"Hold the last frame about {over:.0f} s longer (freeze frame) before cutting on.")
        rows.append((k, start, length, app, line, words, need))

    out = [
        "# VOICEOVER SCRIPT: AnubhavPramaan demo video (internal)",
        "",
        f"For `docs/internal/video/demo-cut.mp4` ({tl['seconds']:.0f} s rough cut, made by `tools/cut_demo.py`). "
        "Generated by `tools/voiceover_script.py` from the cut's real timeline; rerun it after any new cut.",
        "",
        "## How to record (10 minutes)",
        "",
        "1. Quiet room, phone or headset mic a hand's width from your mouth, no fan.",
        "2. Read each block as a separate take and save it as `vo-01.wav`, `vo-02.wav` and so on. "
        "Leave one second of silence at the start and end of each take.",
        f"3. Pace: calm and clear, about {WPS} words a second. The seconds column says how long each line may take.",
        "4. **Silent blocks are the app's own voices** (the question, the worker, the read-back). Do not talk over them.",
        "5. When you lay a take over a section where the app also speaks, lower the app track to about 25 percent "
        "under your voice (ducking) and bring it back after.",
        "",
        "## Script",
        "",
        "| # | Starts at | Seconds there | App audio | Your line | Words, seconds needed |",
        "|---|---|---|---|---|---|",
    ]
    for k, start, length, app, line, words, need in rows:
        app_txt = app or "none"
        line_txt = f"**{line}**" if line else "*(silent: let the app speak)*"
        need_txt = f"{words} words, {need:.1f} s" if line else ""
        out.append(f"| {k} | {mmss(start)} | {length:.1f} | {app_txt} | {line_txt} | {need_txt} |")
    out += [
        "",
        f"Total: {words_total} words, about {words_total / WPS:.0f} s of voice in a {tl['seconds']:.0f} s video.",
        "",
        "## Holds to add while editing",
        "",
    ]
    out += [f"- {h}" for h in holds] or ["- None needed."]
    out += [
        "",
        "## Edit, then upload",
        "",
        "1. Put `demo-cut.mp4` on the timeline, your takes on a second audio track at the times above.",
        "2. Keep the on-screen captions; the one that says the worker's voice is synthetic must stay visible.",
        "3. Export 1080p, H.264, AAC. Keep it under about 3 minutes.",
        "4. YouTube: upload as **Unlisted**, then open the link in a private window to check it plays while logged out.",
        "",
        "**Title:** AnubhavPramaan: AI-assisted RPL assessment | SIH 2026, SIH26242 | Team PixelPaws",
        "",
        "**Description:**",
        "",
        "AnubhavPramaan (अनुभव प्रमाण, proof of experience) is our idea for Smart India Hackathon 2026, problem statement "
        "SIH26242 of the Ministry of Skill Development and Entrepreneurship: an AI-assisted skill assessment tool for "
        "Recognition of Prior Learning. A worker describes their work by voice in Hindi, the tool matches it to an NSQF "
        "Qualification Pack using NCVET's own 70% rule, the assessor scores the practical against anchored criteria with "
        "evidence, and only the assessor signs a tamper-evident record anyone can verify. The AI suggests; the assessor decides.",
        "",
        "This demo runs the working prototype. The worker's answers are role-play, spoken by a synthetic voice. Speech in "
        "the prototype uses ElevenLabs as a stand-in while our Bhashini key is pending; production uses Bhashini.",
        "",
        "Code: https://github.com/MONSTERBOY110/AnubhavPramaan",
        "",
        "Chapters:",
    ]
    chapters = [(0, "Introduction"), (rows[1][1], "Bolo: the worker speaks"), (rows[8][1], "Milao: qualification match"),
                (rows[9][1], "Parkho: practical assessment"), (rows[12][1], "Pramaan: sign-off and record"),
                (rows[14][1], "Samaan: assessor consistency")]
    out += [f"{int(t // 60)}:{int(t % 60):02d} {name}" for t, name in chapters]
    out += [
        "",
        "Chapter times match the rough cut; shift them if your edit adds holds.",
        "",
    ]
    OUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {OUT} ({words_total} words)")
    for h in holds:
        print("  hold:", h)


if __name__ == "__main__":
    main()
